In [15]:
# 一元线性回归分析例子
from sklearn import datasets
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
import numpy as np

In [16]:
# 生成连续的值
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [17]:
# 生成误差
np.random.uniform(2, -2, 50)

array([-1.82885838, -0.76635406, -1.65540347, -0.16987159,  0.31844044,
       -1.78950938, -1.55705611,  0.76306688, -0.17534808, -1.71720685,
       -1.18502283,  1.01156706, -1.31351658,  0.52079003,  1.76599618,
       -1.65804726,  0.71807602, -0.37664803,  1.45473972,  0.68993968,
        1.57308839, -0.30134245, -1.38762869,  0.84968414, -1.73082706,
       -0.44240892,  1.85705083, -1.24256397, -0.60247089, -0.24836815,
        1.69292228,  0.47066517,  1.26524906, -0.06383775,  0.90668938,
        1.18185267,  1.86594837, -1.73217865,  0.40120901, -0.46231344,
        1.33079442,  0.09082986, -0.51137198, -1.59489242, -1.18545803,
        1.7252702 , -0.10759145,  1.36563469,  1.36045381,  1.39110142])

In [18]:
boston = datasets.load_boston()

In [20]:
b_x = boston.data  # 特征变量
b_y = boston.target  # 目标值
x_train, x_test, y_train, y_test = train_test_split(b_x, b_y, test_size=0.25)

In [21]:
y_train

array([20.6, 14.5,  9.7, 18.2, 14.6, 30.5, 11.7, 19.9, 23.4, 19.5, 22.5,
       18.8, 42.8, 20.6, 18.2, 32.7, 20.4, 19.6, 17.8, 13.9, 10.9, 15.7,
       11.3, 17.2, 19.2, 34.6, 24.3, 48.8, 11.5, 37.6, 42.3, 23.9, 21.9,
       17.1, 22.3, 24.7, 10.2, 50. , 20.6, 18.7, 15.2, 35.4, 15.2, 25. ,
       22.6, 37. , 22.7, 21.1, 24.5, 29.6, 13.4, 31.5, 33.2, 50. , 18.5,
       21.6, 44. , 14.9, 50. , 23.8, 24.2, 10.5, 14.9, 25. , 46.7, 20.5,
       22.6, 19.8, 20.4, 21.4, 13.8, 14.3, 15. , 33.8, 22.6,  7.2, 37.2,
       22.4, 18.3, 19. , 32. , 19.1, 16.2, 18.6, 20. , 15.6, 17.7, 22.8,
       32.9, 12.7, 13.8, 19.4, 27.5, 16.1, 25.2, 24.1, 20.1,  7.2, 24.5,
        7. , 21.4, 20.8, 22.4, 19.6, 24.3, 50. , 12.5, 17.8, 29.4, 17.1,
       14.3,  7. , 22. , 26.6, 19.2, 41.3, 20.3, 13.4, 36. , 18.5, 23.7,
       48.3, 15. , 10.8, 25. , 24.8, 23.2,  8.5, 29.1, 18.2, 23.6, 22.8,
       50. , 17. , 13.3, 50. , 18.9, 14.6, 24.8, 19.1, 35.1, 31. , 28.7,
       46. , 16.3, 31.6, 22.2, 37.9, 10.4, 12.1, 21

In [22]:
b_x

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [23]:
b_y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21